name: Changelog Checker

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  changelog_checker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Changelog Checker
      run: python changelog_checker.py

    - name: Add labels on failure
      uses: peter-evans/create-issue-comment@v1
      if: failure()
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ⚠️ **Changelog Check Failed**

          The changelog is missing or needs to be updated. Please make the necessary changes and resubmit the pull request.
        repo-token: ${{ secrets.GITHUB_TOKEN }}
